import json
import os

path = "Paper/scripts/eq47_51_spatial_overlay.ipynb"
with open(path, "r") as f:
    nb = json.load(f)

for cell in nb["cells"]:
    if cell["cell_type"] == "code":
        source = "".join(cell["source"])
        
        # 1. Update _norm_geoid_11 in Cell 10 to be robust
        if "def _norm_geoid_11(s: pd.Series) -> pd.Series:" in source:
            new_source = [
                "def _norm_geoid_11(s: pd.Series) -> pd.Series:\n",
                "    \"\"\"Census tract GEOID as 11-char string (fixes int/str/float/sci errors).\"\"\"\n",
                "    if s is None or (hasattr(s, 'empty') and s.empty): return s\n",
                "    def _clean(v):\n",
                "        if pd.isna(v): return \"\"\n",
                "        s_v = str(v).strip()\n",
                "        if 'e' in s_v.lower(): # scientific notation fallback\n",
                "            try: s_v = \"{:.0f}\".format(float(s_v))\n",
                "            except: pass\n",
                "        if '.' in s_v: s_v = s_v.split('.')[0]\n",
                "        s_v = \"\".join(filter(str.isdigit, s_v))\n",
                "        if not s_v: return \"\"\n",
                "        return s_v[-11:].zfill(11)\n",
                "    return s.apply(_clean).replace(\"\", pd.NA).astype(\"string\")\n",
                "\n",
                "\n",
                "def load_holc(city: dict):\n",
                "    \"\"\"Load HOLC GeoJSON for a city. Returns None when geopandas is unavailable.\"\"\"\n",
                "    if not GEOPANDAS_AVAILABLE:\n",
                "        return None\n",
                "    path = DATA_DIR / f\"holc_{city['id']}.geojson\"\n",
                "    if not path.exists():\n",
                "        print(f\"  [HOLC] {city['label']}: file not found — run fetch_spatial_data.py\")\n",
                "        return None\n",
                "    try:\n",
                "        gdf = gpd.read_file(path)\n",
                "        if gdf.empty:\n",
                "            print(f\"  [HOLC] {city['label']}: empty GeoDataFrame (stub)\")\n",
                "            return None\n",
                "        # Handle missing CRS in placeholder geojson\n",
                "        if gdf.crs is None: gdf.set_crs(TARGET_CRS, inplace=True)\n",
                "        else: gdf = gdf.to_crs(TARGET_CRS)\n",
                "        # Normalise grade column\n",
                "        for col in [\"holc_grade\", \"grade\", \"HOLC_grade\", \"Grade\"]:\n",
                "            if col in gdf.columns:\n",
                "                gdf = gdf.rename(columns={col: \"holc_grade\"})\n",
                "                break\n",
                "        if \"holc_grade\" not in gdf.columns: gdf[\"holc_grade\"] = \"D\"\n",
                "        gdf[\"holc_d_flag\"] = (gdf[\"holc_grade\"] == \"D\").astype(int)\n",
                "        print(f\"  [HOLC] {city['label']}: {len(gdf)} polygons\")\n",
                "        return gdf\n",
                "    except Exception as exc:\n",
                "        print(f\"  [HOLC] {city['label']}: failed to load ({exc})\")\n",
                "        return None\n",
                "\n",
                "\n",
                "def load_acs(city: dict):\n",
                "    \"\"\"Load ACS CSV for a city.\"\"\"\n",
                "    path = DATA_DIR / f\"acs_{city['id']}.csv\"\n",
                "    if not path.exists():\n",
                "        print(f\"  [ACS]  {city['label']}: file not found\")\n",
                "        return None\n",
                "    try:\n",
                "        df = pd.read_csv(path, comment=\"#\")\n",
                "        if df.empty: return None\n",
                "        rename_map = {\n",
                "            \"B02001_001E\": \"acs_total_pop\",\n",
                "            \"B02001_002E\": \"acs_white_pop\",\n",
                "            \"B02001_003E\": \"acs_black_pop\",\n",
                "            \"B19013_001E\": \"acs_median_income\",\n",
                "        }\n",
                "        df = df.rename(columns=rename_map)\n",
                "        for col in [\"acs_total_pop\", \"acs_white_pop\", \"acs_black_pop\", \"acs_median_income\"]:\n",
                "            if col in df.columns:\n",
                "                df[col] = pd.to_numeric(df[col], errors=\"coerce\")\n",
                "        df[\"acs_pct_black\"] = (df[\"acs_black_pop\"] / df[\"acs_total_pop\"].replace(0, np.nan) * 100)\n",
                "        df[\"acs_pct_white\"] = (df[\"acs_white_pop\"] / df[\"acs_total_pop\"].replace(0, np.nan) * 100)\n",
                "        if \"GEO_ID\" in df.columns:\n",
                "            df[\"GEOID\"] = df[\"GEO_ID\"].str.replace(\"1400000US\", \"\", regex=False).str.strip()\n",
                "        elif {\"state\", \"county\", \"tract\"}.issubset(df.columns):\n",
                "            df[\"GEOID\"] = (df[\"state\"].astype(str).str.zfill(2) + \n",
                "                          df[\"county\"].astype(str).str.zfill(3) + \n",
                "                          df[\"tract\"].astype(str).str.zfill(6))\n",
                "        if \"GEOID\" in df.columns: df[\"GEOID\"] = _norm_geoid_11(df[\"GEOID\"])\n",
                "        print(f\"  [ACS]  {city['label']}: {len(df)} tracts\")\n",
                "        return df\n",
                "    except Exception as exc:\n",
                "        print(f\"  [ACS]  {city['label']}: failed ({exc})\")\n",
                "        return None\n",
                "\n",
                "\n",
                "def load_ejscreen(city: dict):\n",
                "    \"\"\"Load EJScreen CSV for a city.\"\"\"\n",
                "    path = DATA_DIR / f\"ejscreen_{city['id']}.csv\"\n",
                "    if not path.exists():\n",
                "        print(f\"  [EJS]  {city['label']}: file not found\")\n",
                "        return None\n",
                "    try:\n",
                "        df = pd.read_csv(path, comment=\"#\", encoding=\"latin-1\", low_memory=False)\n",
                "        if df.empty: return None\n",
                "        rename_map = {\"ID\": \"GEOID\", \"LDPNT\": \"lead_paint_index\", \"PTRAF\": \"highway_buffer_proxy\"}\n",
                "        df = df.rename(columns={k: v for k, v in rename_map.items() if k in df.columns})\n",
                "        if \"GEOID\" in df.columns: df[\"GEOID\"] = _norm_geoid_11(df[\"GEOID\"])\n",
                "        for col in [\"lead_paint_index\", \"highway_buffer_proxy\"]:\n",
                "            if col in df.columns: df[col] = pd.to_numeric(df[col], errors=\"coerce\")\n",
                "        print(f\"  [EJS]  {city['label']}: {len(df)} tracts\")\n",
                "        return df\n",
                "    except Exception as exc:\n",
                "        print(f\"  [EJS]  {city['label']}: failed ({exc})\")\n",
                "        return None\n",
                "\n",
                "\n",
                "def load_gva(city: dict):\n",
                "    \"\"\"Load GVA incidents CSV for a city (stub-aware).\"\"\"\n",
                "    path = DATA_DIR / f\"gva_incidents_{city['id']}.csv\"\n",
                "    if not path.exists():\n",
                "        print(f\"  [GVA]  {city['label']}: file not found\")\n",
                "        return None\n",
                "    try:\n",
                "        text = path.read_text()\n",
                "        if \"DATA_GAP\" in text: return None\n",
                "        df = pd.read_csv(path, comment=\"#\")\n",
                "        print(f\"  [GVA]  {city['label']}: {len(df)} incidents\")\n",
                "        return df\n",
                "    except Exception as exc:\n",
                "        print(f\"  [GVA]  {city['label']}: failed ({exc})\")\n",
                "        return None\n",
                "\n",
                "\n",
                "def load_cdc_wonder(city: dict):\n",
                "    \"\"\"Load CDC WONDER fallback firearm mortality (county-level stub-aware).\"\"\"\n",
                "    path = DATA_DIR / f\"cdc_wonder_firearm_{city['id']}.csv\"\n",
                "    if not path.exists(): return None\n",
                "    try:\n",
                "        text = path.read_text()\n",
                "        if \"DATA_GAP\" in text: return None\n",
                "        return pd.read_csv(path, comment=\"#\")\n",
                "    except Exception: return None\n",
                "\n",
                "\n",
                "def load_ppi(city: dict):\n",
                "    \"\"\"Load PPI incarceration origin CSV (tract/county level, stub-aware).\"\"\"\n",
                "    path = DATA_DIR / f\"ppi_{city['id']}.csv\"\n",
                "    if not path.exists():\n",
                "        print(f\"  [PPI]  {city['label']}: file not found\")\n",
                "        return None\n",
                "    try:\n",
                "        text = path.read_text()\n",
                "        if \"DATA_GAP\" in text: return None\n",
                "        df = pd.read_csv(path, comment=\"#\")\n",
                "        if \"GEOID\" in df.columns: df[\"GEOID\"] = _norm_geoid_11(df[\"GEOID\"])\n",
                "        df[\"ppi_data_level\"] = city[\"ppi_level\"]\n",
                "        print(f\"  [PPI]  {city['label']}: {len(df)} rows ({city['ppi_level']}-level)\")\n",
                "        return df\n",
                "    except Exception as exc:\n",
                "        print(f\"  [PPI]  {city['label']}: failed ({exc})\")\n",
                "        return None\n"
            ]
            cell["source"] = new_source
            print("Updated robust _norm_geoid_11.")

        # 2. Update build_tract_grid in Cell 11 to use the global helper
        if "def build_tract_grid(city: dict):" in source:
            new_source = [
                "def build_tract_grid(city: dict):\n",
                "    \"\"\"\n",
                "    Load Census tract boundaries via the Census TIGER WMS API.\n",
                "    Returns an empty DataFrame when geopandas is unavailable (triggers synthetic fallback).\n",
                "    \"\"\"\n",
                "    if not GEOPANDAS_AVAILABLE:\n",
                "        return pd.DataFrame({\"GEOID\": []})\n",
                "\n",
                "    import requests\n",
                "    import io\n",
                "    county_fips = city[\"fips_county\"]\n",
                "    state_fips  = county_fips[:2]\n",
                "    county_code = county_fips[2:]\n",
                "    url = (\n",
                "        \"https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/\"\n",
                "        \"tigerWMS_Census2020/MapServer/8/query\"\n",
                "    )\n",
                "    params = {\n",
                "        \"where\": f\"STATE='{state_fips}' AND COUNTY='{county_code}'\",\n",
                "        \"outFields\": \"GEOID,AREALAND,AREAWATER\",\n",
                "        \"returnGeometry\": \"true\",\n",
                "        \"f\": \"geojson\",\n",
                "    }\n",
                "    try:\n",
                "        # Detailed print for debugging TIGER issues\n",
                "        # print(f\"  [TIGER] Requesting: {state_fips}-{county_code}\")\n",
                "        r = requests.get(url, params=params, timeout=60)\n",
                "        r.raise_for_status()\n",
                "        gdf = gpd.read_file(io.BytesIO(r.content))\n",
                "        if gdf.empty:\n",
                "             print(f\"  [TIGER] {city['label']}: API returned zero tracts (Empty set)\")\n",
                "             return gdf\n",
                "        gdf = gdf.to_crs(TARGET_CRS)\n",
                "        if \"GEOID\" in gdf.columns:\n",
                "            gdf[\"GEOID\"] = _norm_geoid_11(gdf[\"GEOID\"])\n",
                "        print(f\"  [TIGER] {city['label']}: {len(gdf)} tracts\")\n",
                "        return gdf\n",
                "    except Exception as exc:\n",
                "        print(f\"  [TIGER] {city['label']}: failed ({exc}) — synthetic data fallback\")\n",
                "        return gpd.GeoDataFrame({\"GEOID\": [], \"geometry\": []}, crs=TARGET_CRS)\n",
                "\n",
                "\n",
                "def spatial_join_holc(tracts, holc):\n",
                "    \"\"\"Assign HOLC grade to each tract via centroid-within-polygon join.\"\"\"\n",
                "    if holc is None or (hasattr(holc, 'empty') and holc.empty):\n",
                "        tracts[\"holc_grade\"]  = np.nan\n",
                "        tracts[\"holc_d_flag\"] = 0\n",
                "        return tracts\n",
                "    if not GEOPANDAS_AVAILABLE or tracts.empty:\n",
                "        tracts[\"holc_grade\"]  = np.nan\n",
                "        tracts[\"holc_d_flag\"] = 0\n",
                "        return tracts\n",
                "\n",
                "    try:\n",
                "        centroids = tracts.copy()\n",
                "        centroids.geometry = tracts.geometry.centroid\n",
                "        joined = gpd.sjoin(\n",
                "            centroids[[\"GEOID\", \"geometry\"]],\n",
                "            holc[[\"holc_grade\", \"holc_d_flag\", \"geometry\"]],\n",
                "            how=\"left\", predicate=\"within\"\n",
                "        ).reset_index(drop=True)\n",
                "        \n",
                "        grade_order = {\"A\": 1, \"B\": 2, \"C\": 3, \"D\": 4}\n",
                "        joined[\"grade_rank\"] = joined[\"holc_grade\"].map(grade_order).fillna(0)\n",
                "        joined = joined.sort_values([\"GEOID\", \"grade_rank\"], ascending=[True, False])\n",
                "        joined = joined.drop_duplicates(subset=[\"GEOID\"])\n",
                "\n",
                "        tracts = tracts.merge(\n",
                "            joined[[\"GEOID\", \"holc_grade\", \"holc_d_flag\"]],\n",
                "            on=\"GEOID\", how=\"left\"\n",
                "        )\n",
                "        n_matched = tracts[\"holc_grade\"].notna().sum()\n",
                "        print(f\"  [JOIN]  HOLC: {n_matched}/{len(tracts)} tracts assigned a grade\")\n",
                "    except Exception as exc:\n",
                "        print(f\"  [JOIN]  HOLC failed: {exc}\")\n",
                "    return tracts\n",
                "\n",
                "\n",
                "def gva_to_tract_density(gva, tracts):\n",
                "    \"\"\"Convert GVA point incidents to per-tract count density.\"\"\"\n",
                "    tracts[\"firearm_density_gva\"] = np.nan\n",
                "    if gva is None or (hasattr(gva, 'empty') and gva.empty) or tracts.empty:\n",
                "        return tracts\n",
                "    if not GEOPANDAS_AVAILABLE or not {\"latitude\", \"longitude\"}.issubset(gva.columns):\n",
                "        return tracts\n",
                "    try:\n",
                "        gva_pts = gpd.GeoDataFrame(\n",
                "            gva,\n",
                "            geometry=gpd.points_from_xy(gva[\"longitude\"], gva[\"latitude\"]),\n",
                "            crs=TARGET_CRS\n",
                "        )\n",
                "        gva_pts = gva_pts.dropna(subset=[\"geometry\"])\n",
                "        joined = gpd.sjoin(\n",
                "            gva_pts[[\"geometry\"]],\n",
                "            tracts[[\"GEOID\", \"geometry\"]],\n",
                "            how=\"left\", predicate=\"within\"\n",
                "        )\n",
                "        counts = joined.groupby(\"GEOID\").size().rename(\"firearm_density_gva\")\n",
                "        tracts = tracts.merge(counts, on=\"GEOID\", how=\"left\", suffixes=(\"\", \"_new\"))\n",
                "        if \"firearm_density_gva_new\" in tracts.columns:\n",
                "            tracts[\"firearm_density_gva\"] = tracts[\"firearm_density_gva_new\"].fillna(0)\n",
                "            tracts = tracts.drop(columns=[\"firearm_density_gva_new\"])\n",
                "        else:\n",
                "            tracts[\"firearm_density_gva\"] = tracts[\"firearm_density_gva\"].fillna(0)\n",
                "    except Exception as exc:\n",
                "        print(f\"  [GVA]  Density join failed: {exc}\")\n",
                "    return tracts\n"
            ]
            cell["source"] = new_source
            print("Updated build_tract_grid and telemetry.")

with open(path, "w") as f:
    json.dump(nb, f, indent=1)
