#!/usr/bin/env bash
# Rebuild 00_ROOT_The_Open_Source_Republic.md from:
#   - 00_ROOT_SERIES_FRAGMENT.md (shared series block only)
#   - Episode_00 … Episode_21 (verbatim), in broadcast order
set -euo pipefail
DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$DIR"

OUT="00_ROOT_The_Open_Source_Republic.md"
FRAG="00_ROOT_SERIES_FRAGMENT.md"

if [[ ! -f "$FRAG" ]]; then
  echo "error: missing $FRAG" >&2
  exit 1
fi

{
  shopt -s nullglob
  cat <<'BUNDLE_HEADER'
> **⚠️ AUTO-GENERATED FILE** — Do not edit this file directly.
> It is rebuilt by running `./build_full_series_prompt.sh` from:
> - `00_ROOT_SERIES_FRAGMENT.md` (the shared series block)
> - All `Episode_NN_*.md` files (episode-specific rules and content)
> **Edit those source files instead.**

BUNDLE_HEADER
  echo ""
  cat "$FRAG"
  echo ""
  echo "## Verbatim episode prompts (Episode 0 + Episodes 1–21)"
  echo ""
  echo "The sections below are the **complete** contents of each \`Episode_NN_*.md\` file, concatenated in broadcast order."
  echo ""
  for n in 00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21; do
    matches=( Episode_${n}_*.md )
    if [[ ${#matches[@]} -ne 1 ]]; then
      echo "error: expected exactly one Episode_${n}_*.md, got ${#matches[@]}: ${matches[*]-}" >&2
      exit 1
    fi
    f="${matches[0]}"
    echo ""
    echo "---"
    echo ""
    echo "### FILE: \`$f\` (verbatim full text follows)"
    echo ""
    echo "---"
    echo ""
    cat "$f"
  done
} > "${OUT}.tmp"
mv "${OUT}.tmp" "$OUT"
echo "wrote $OUT ($(wc -l < "$OUT") lines)"
