export interface EquationSymbol {
  id: string;
  latex: string;
  name: string;
  plainPhrase: string;
  meaning: string;
  units?: string;
  sourceNote?: string;
}

const symbol = (entry: EquationSymbol): EquationSymbol => entry;

export const equationSymbols = {
  reform: symbol({ id: 'reform', latex: 'R_i', name: 'Reform', plainPhrase: 'each non-kinetic reform', meaning: 'One legislative, judicial, or policy intervention in the historical reform set.' }),
  reformSet: symbol({ id: 'reform-set', latex: '\\mathcal{R}', name: 'Reform set', plainPhrase: 'the set of non-kinetic reforms', meaning: 'The collection of non-kinetic reforms examined across the framework dataset.' }),
  deltaMax: symbol({ id: 'delta-max', latex: '\\Delta\\max', name: 'Change in extraction ceiling', plainPhrase: 'changes the extraction ceiling', meaning: 'The change in the Elite extraction share associated with an intervention.' }),
  zero: symbol({ id: 'zero', latex: '0', name: 'Zero change', plainPhrase: 'by zero', meaning: 'No sustained change in the measured quantity.' }),

  capacity1450: symbol({ id: 'capacity-1450', latex: 'O_{1450}^{\\text{capacity}}', name: '1450 capacity', plainPhrase: 'the pre-racialization capacity baseline', meaning: 'The modeled Out-group capacity baseline before the policy sequence.' }),
  capacity1619: symbol({ id: 'capacity-1619', latex: 'O_{1619}^{\\text{capacity}}', name: '1619 capacity', plainPhrase: 'capacity after enslavement', meaning: 'Residual Out-group capacity after the enslavement policy shock.' }),
  capacity1865: symbol({ id: 'capacity-1865', latex: 'O_{1865}^{\\text{capacity}}', name: '1865 capacity', plainPhrase: 'capacity after the Thirteenth Amendment exception', meaning: 'Residual Out-group capacity after the second policy shock.' }),
  capacity1934: symbol({ id: 'capacity-1934', latex: 'O_{1934}^{\\text{capacity}}', name: '1934 capacity', plainPhrase: 'capacity after redlining', meaning: 'Residual Out-group capacity after the third policy shock.' }),
  capacity1971: symbol({ id: 'capacity-1971', latex: 'O_{1971}^{\\text{capacity}}', name: '1971 capacity', plainPhrase: 'capacity after the War on Drugs', meaning: 'Residual Out-group capacity after all listed policy shocks.' }),
  alpha: symbol({ id: 'alpha', latex: '\\alpha', name: 'Enslavement effect', plainPhrase: 'the enslavement reduction factor', meaning: 'The modeled fraction of capacity removed through chattel enslavement.' }),
  beta: symbol({ id: 'beta', latex: '\\beta', name: 'Thirteenth Amendment effect', plainPhrase: 'the Thirteenth Amendment reduction factor', meaning: 'The modeled capacity reduction associated with the exception clause and its enforcement system.' }),
  gamma: symbol({ id: 'gamma', latex: '\\gamma', name: 'Redlining effect', plainPhrase: 'the redlining reduction factor', meaning: 'The modeled capacity reduction associated with redlining.' }),
  delta: symbol({ id: 'delta', latex: '\\delta', name: 'War on Drugs effect', plainPhrase: 'the War on Drugs reduction factor', meaning: 'The modeled capacity reduction associated with asymmetric drug enforcement.' }),
  enslavementPolicy: symbol({ id: 'policy-enslavement', latex: 'P_{\\text{enslavement}}', name: 'Enslavement policy', plainPhrase: 'enslavement policy', meaning: 'The historical policy regime that applies the enslavement capacity shock.' }),
  amendmentPolicy: symbol({ id: 'policy-amendment', latex: 'P_{\\text{13thAmendment}}', name: 'Thirteenth Amendment policy', plainPhrase: 'the Thirteenth Amendment exception policy', meaning: 'The post-emancipation policy regime associated with the exception clause.' }),
  redliningPolicy: symbol({ id: 'policy-redlining', latex: 'P_{\\text{redlining}}', name: 'Redlining policy', plainPhrase: 'redlining policy', meaning: 'The housing and credit policy regime that applies the redlining shock.' }),
  drugsPolicy: symbol({ id: 'policy-drugs', latex: 'P_{\\text{WarOnDrugs}}', name: 'War on Drugs policy', plainPhrase: 'War on Drugs policy', meaning: 'The enforcement regime that applies the final listed capacity shock.' }),

  classPower: symbol({ id: 'class-power', latex: 'P_{\\text{class}}(t)', name: 'Class-band power', plainPhrase: 'class-coherence power', meaning: 'Power in the low-frequency class-attention band at time t.' }),
  threshold: symbol({ id: 'threshold', latex: '\\tau', name: 'Crash threshold', plainPhrase: 'the structural-response threshold', meaning: 'Critical amplitude of effective threat at which the Elite mode-shifts from extraction maintenance to structural response.', units: 'dimensionless threshold score', sourceNote: 'Name, meaning, and units adapted from systemic_arbitrage/variables.yaml.' }),
  kineticMomentum: symbol({ id: 'kinetic-momentum', latex: 'T', name: 'Kinetic momentum', plainPhrase: 'class-coherence threat', meaning: 'Class-coherence threat or mobilized pressure from subordinate groups.', units: 'dimensionless z-score', sourceNote: 'Definition and units from systemic_arbitrage/variables.yaml.' }),
  enclosureVolts: symbol({ id: 'enclosure-volts', latex: 'V_E', name: 'Enclosure volts', plainPhrase: 'Elite suppression allocation', meaning: 'Elite suppression allocation directed against perceived threats to the extraction kernel.', units: 'dimensionless z-score', sourceNote: 'Definition and units from systemic_arbitrage/variables.yaml.' }),
  orthographicIllusion: symbol({ id: 'orthographic-illusion', latex: 'O_x', name: 'Orthographic illusion index', plainPhrase: 'identity-band noise ratio', meaning: 'Ratio of high-frequency identity-band noise to total spectral power.', units: 'ratio', sourceNote: 'Definition and units from systemic_arbitrage/variables.yaml.' }),
  realKineticMomentum: symbol({ id: 'real-kinetic-momentum', latex: 'P_{\\text{real}}', name: 'Real kinetic momentum', plainPhrase: 'low-frequency structural attention', meaning: 'Low-frequency structural component of collective attention reflecting durable economic anxiety and class-coherence pressure.', units: 'dimensionless z-score', sourceNote: 'Definition and units from systemic_arbitrage/variables.yaml.' }),
  effectiveThreat: symbol({ id: 'effective-threat', latex: 'M_{\\text{eff}}', name: 'Effective threat', plainPhrase: 'effective structural threat', meaning: 'Structural threat after discounting for psychological-wage interference.', units: 'dimensionless', sourceNote: 'Definition and units from systemic_arbitrage/variables.yaml.' }),
  identityPower: symbol({ id: 'identity-power', latex: 'P_{\\text{id}}(t)', name: 'Identity-band power', plainPhrase: 'identity-band attention', meaning: 'Power routed into higher-frequency identity-attention modes at time t.' }),
  noisePower: symbol({ id: 'noise-power', latex: 'P_{\\eta}', name: 'Noise power', plainPhrase: 'unstructured attention', meaning: 'Residual political attention carried by the broadband noise floor.' }),
  constantTotal: symbol({ id: 'constant-total', latex: '\\mathrm{const.}', name: 'Conserved total', plainPhrase: 'a conserved total variance', meaning: 'The fixed sum of class-band, identity-band, and noise power under the stated constraint.' }),

  circularMean: symbol({ id: 'circular-mean', latex: '\\overline{e^{i\\Phi}}', name: 'Circular mean vector', plainPhrase: 'the mean phase vector', meaning: 'The average of the unit vectors representing subgroup phase values.' }),
  sampleCount: symbol({ id: 'sample-count', latex: 'N', name: 'Subgroup count', plainPhrase: 'the number of subgroups', meaning: 'The number of phase observations included in the circular mean.', units: 'count' }),
  sampleIndex: symbol({ id: 'sample-index', latex: 'j', name: 'Subgroup index', plainPhrase: 'each subgroup index', meaning: 'The index identifying one subgroup in the phase distribution.' }),
  phaseValue: symbol({ id: 'phase-value', latex: '\\Phi_j', name: 'Subgroup phase', plainPhrase: 'each subgroup phase', meaning: 'The angular displacement assigned to subgroup j.', units: 'radians' }),
  phaseLoad: symbol({ id: 'phase-load', latex: '\\Phi_{\\text{load}}(t)', name: 'Phase load', plainPhrase: 'phase fragmentation', meaning: 'Circular dispersion at time t, ranging from perfect coherence to maximum cancellation.', units: '0–1 index' }),

  enclosureScore: symbol({ id: 'enclosure-score', latex: '\\mathcal{S}_{\\text{enc}}', name: 'Enclosure Score', plainPhrase: 'the composite enclosure score', meaning: 'The normalized magnitude of material and psychological enclosure.', units: '0–1 index' }),
  normalization: symbol({ id: 'normalization', latex: '\\frac{1}{\\sqrt{2}}', name: 'Normalization factor', plainPhrase: 'normalized by the maximum possible magnitude', meaning: 'The reciprocal of the maximum two-channel norm, which pins total enclosure to 1.0.' }),
  materialScore: symbol({ id: 'material-score', latex: '\\mathcal{S}_{\\text{mat}}', name: 'Material enclosure', plainPhrase: 'material enclosure', meaning: 'The composite of communal-capacity and mobility obstruction.', units: '0–1 index' }),
  psychologicalScore: symbol({ id: 'psychological-score', latex: '\\mathcal{S}_{\\text{psych}}', name: 'Psychological enclosure', plainPhrase: 'psychological enclosure', meaning: 'The obstruction of psychological and epistemic autonomy.', units: '0–1 index' }),
  communalObstruction: symbol({ id: 'communal-obstruction', latex: 'e_1', name: 'Communal-capacity obstruction', plainPhrase: 'communal-capacity obstruction', meaning: 'Obstruction of internal economic, social, educational, kinship, and mutual-aid infrastructure.', units: '0–1 index' }),
  mobilityObstruction: symbol({ id: 'mobility-obstruction', latex: 'e_2', name: 'Mobility obstruction', plainPhrase: 'mobility obstruction', meaning: 'Obstruction of movement, market access, property access, employment pathways, and exit.', units: '0–1 index' }),
  epistemicObstruction: symbol({ id: 'epistemic-obstruction', latex: 'e_3', name: 'Epistemic obstruction', plainPhrase: 'epistemic obstruction', meaning: 'Obstruction of the capacity to name and model the enclosure.', units: '0–1 index' }),

  imaginaryUnit: symbol({ id: 'imaginary-unit', latex: 'j', name: 'Imaginary unit', plainPhrase: 'the orthogonal status channel', meaning: 'The imaginary unit marking a component orthogonal to material reality.' }),
  statusWage: symbol({ id: 'status-wage', latex: '\\psi_s', name: 'Psychological/status wage', plainPhrase: 'the psychological status wage', meaning: 'A non-material allocation of status, deference, and relative social position.' }),
  bufferClass: symbol({ id: 'buffer-class', latex: 'I_{\\text{buffer}}', name: 'Buffer Class', plainPhrase: 'the Buffer Class', meaning: 'The population positioned between the Elite and the racialized Out-group.' }),
  racializedOutgroup: symbol({ id: 'racialized-outgroup', latex: 'O_{\\text{racialized}}', name: 'Racialized Out-group', plainPhrase: 'the racialized Out-group', meaning: 'The population positioned as the primary target of extraction and enclosure.' }),
  solidarity: symbol({ id: 'solidarity', latex: '\\text{Solidarity}', name: 'Cross-group solidarity', plainPhrase: 'cross-group solidarity', meaning: 'Collective alignment between the Buffer Class and the racialized Out-group.' }),
  vulnerability: symbol({ id: 'vulnerability', latex: '\\text{Vulnerability}', name: 'Buffer vulnerability', plainPhrase: 'Buffer Class vulnerability', meaning: 'Exposure of the Buffer Class to Elite extraction after coalition capacity falls.' }),
  extraction: symbol({ id: 'extraction', latex: '\\mathcal{E}', name: 'Extraction output', plainPhrase: 'time-indexed extraction output', meaning: 'Extraction output routed toward the Elite.', sourceNote: 'Name and meaning from Paper/The_Original_Power.tex:9397–9400.' }),

  enforcementClass: symbol({ id: 'enforcement-class', latex: 'F_{\\text{enforce}}', name: 'Enforcement Class', plainPhrase: 'the physical actuator of the partition', meaning: 'The coercive layer that makes law, property, borders, debt, and discipline executable.', sourceNote: 'Name and meaning from Paper/The_Original_Power.tex:408–410.' }),
  leadPolicy: symbol({ id: 'lead-policy', latex: 'P_{\\text{lead}}', name: 'Environmental lead policy variable', plainPhrase: 'the environmental lead policy variable', meaning: 'The deliberate and then deliberately concealed mass deployment of a neurotoxin, modeled at population level.', sourceNote: 'Name and meaning from Paper/The_Original_Power.tex:7801–7805.' }),
  biologicalDepletion: symbol({ id: 'biological-depletion', latex: '\\beta_{\\text{bio}}', name: 'Biological depletion coefficient', plainPhrase: 'the biological depletion coefficient', meaning: 'The multiplicative product of environmental toxicant concentration, cumulative exposure time, and age-dependent absorption rate.', units: 'Composite: concentration in μg/dL blood equivalent or ambient ppm; exposure time in years', sourceNote: 'Name, meaning, and component units from Paper/chapter_environmental_racism.tex:50–68.' }),
  toxicantConcentration: symbol({ id: 'toxicant-concentration', latex: 'E(t)', name: 'Environmental toxicant concentration vector', plainPhrase: 'environmental toxicant concentration', meaning: 'The composite of atmospheric, waterborne, particulate, and product-level toxicant loading.', units: 'μg/dL blood equivalent or ambient ppm', sourceNote: 'Name, meaning, and units from Paper/chapter_environmental_racism.tex:59–78.' }),
  exposureTime: symbol({ id: 'exposure-time', latex: 'T(t)', name: 'Cumulative exposure time', plainPhrase: 'cumulative exposure time', meaning: 'The time function capturing years of toxicant contact.', units: 'years', sourceNote: 'Name, meaning, and units from Paper/chapter_environmental_racism.tex:59–82.' }),
  absorptionRate: symbol({ id: 'absorption-rate', latex: 'A(t)', name: 'Age-dependent absorption rate', plainPhrase: 'age-dependent absorption', meaning: 'The absorption rate that peaks during prenatal and early-childhood developmental windows.', sourceNote: 'Name and meaning from Paper/chapter_environmental_racism.tex:61–86.' }),
  developmentalLag: symbol({ id: 'developmental-lag', latex: '\\tau_{\\text{age}}', name: 'Developmental lag', plainPhrase: 'the developmental lag', meaning: 'The delay between lead exposure and the modeled behavioral output.', units: '21–23 years', sourceNote: 'Name, meaning, and units from Paper/chapter_environmental_racism.tex:324–334.' }),
  biologicalCapacity: symbol({ id: 'biological-capacity', latex: 'O_{\\text{bio}}', name: 'Biological capacity', plainPhrase: 'the biological substrate’s functional capacity', meaning: 'The inherited biological substrate whose functional capacity is diminished by accumulated toxicant load.', sourceNote: 'Name and meaning from Paper/chapter_environmental_racism.tex:88–103.' }),
  propertyTaxLoop: symbol({ id: 'property-tax-loop', latex: 'L_{\\text{loop}}', name: 'Property-tax lead feedback loop', plainPhrase: 'the property-tax lead feedback loop', meaning: 'The causal pipeline in which redlining sets the initial condition, property taxation propagates the differential, and infrastructure age determines toxicant delivery efficiency.', sourceNote: 'Name and meaning from Paper/chapter_environmental_racism.tex:154–169.' }),
  lifetimeExposure: symbol({ id: 'lifetime-exposure', latex: 'M_{\\text{lifetime}}', name: 'Lifetime exposure integral', plainPhrase: 'lifetime menstrual-product metal exposure', meaning: 'Time-varying product metal concentration multiplied by mucosal absorption efficiency and integrated across the total reproductive lifespan.', sourceNote: 'Name and meaning from Paper/chapter_environmental_racism.tex:436–445.' }),
  shadowCapital: symbol({ id: 'shadow-capital', latex: 'C_{\\text{shadow}}', name: 'Shadow capital injection', plainPhrase: 'shadow capital', meaning: 'Capital supplied outside formal state channels through kinetic, financial, and logistical streams.', sourceNote: 'Name and meaning from Paper/chapter_geopolitical_patch.tex:26–42.' }),
  clearanceKinetic: symbol({ id: 'clearance-kinetic', latex: '\\alpha_{\\text{kinetic}}', name: 'Direct kinetic clearance', plainPhrase: 'direct kinetic clearance', meaning: 'Military operations that destroyed villages and expelled inhabitants.', sourceNote: 'Name and meaning from Paper/chapter_geopolitical_patch.tex:68–78.' }),
  clearanceTerror: symbol({ id: 'clearance-terror', latex: '\\alpha_{\\text{terror}}', name: 'Aerosolized terror', plainPhrase: 'aerosolized terror', meaning: 'Massacres that generated panic-driven flight.', sourceNote: 'Name and meaning from Paper/chapter_geopolitical_patch.tex:68–78.' }),
  clearanceAdmin: symbol({ id: 'clearance-admin', latex: '\\alpha_{\\text{admin}}', name: 'Administrative erasure', plainPhrase: 'administrative erasure', meaning: 'Denial of return rights, property confiscation, and demolition of emptied villages.', sourceNote: 'Name and meaning from Paper/chapter_geopolitical_patch.tex:68–78.' }),
  legalDisplay: symbol({ id: 'legal-display', latex: '\\mathcal{L}_{\\text{display}}', name: 'Observable legal constraint', plainPhrase: 'the displayed legal constraint', meaning: 'The observable legal constraint presented through the formal interface.', sourceNote: 'Name and meaning from Paper/chapter_geopolitical_patch.tex:365–372.' }),
  legalBackend: symbol({ id: 'legal-backend', latex: '\\mathcal{L}_{\\text{backend}}', name: 'Operational legal constraint', plainPhrase: 'the backend legal constraint', meaning: 'The actual operational constraint on Elite capital.', sourceNote: 'Name and meaning from Paper/chapter_geopolitical_patch.tex:365–372.' }),
  schoolPrisonThroughput: symbol({ id: 'school-prison-throughput', latex: '\\Phi_{\\text{s2p}}', name: 'School-to-prison pipeline throughput', plainPhrase: 'school-to-prison pipeline throughput', meaning: 'The multiplicative throughput produced by disparate discipline, police presence, zero-tolerance severity, early tracking, and lead-induced behavioral flagging.', sourceNote: 'Name and meaning from Paper/chapter_pipeline_scaffolding.tex:96–105.' }),
  cascadeTransfer: symbol({ id: 'cascade-transfer', latex: 'H_{\\text{cascade}}', name: 'Cascade transfer function', plainPhrase: 'the cascade transfer function', meaning: 'The series product of the redlining, funding, infrastructure, lead, discipline, and incarceration transfer functions.', sourceNote: 'Name and meaning from Paper/chapter_pipeline_scaffolding.tex:194–203.' }),
  targetPopulation: symbol({ id: 'target-population', latex: 'O_{\\text{target}}', name: 'Target population', plainPhrase: 'the target population', meaning: 'The population sorted between immediate liquidation and temporary preservation for forced-labor extraction.', sourceNote: 'Name and meaning from Paper/chapter_german_extraction_algorithm.tex:200–208.' }),
  absorbedPower: symbol({ id: 'absorbed-power', latex: 'P_{\\text{abs}}', name: 'Absorbed power', plainPhrase: 'power absorbed by the load', meaning: 'The portion of the incident suppression signal absorbed by the population and not returned.', sourceNote: 'Name and meaning from Paper/apx_extraction_chart.tex:82–96.' }),

  complexWage: symbol({ id: 'complex-wage', latex: 'W', name: 'Complex Wage', plainPhrase: 'the total suppression allocation', meaning: 'The combined material and psychological allocation represented as a complex quantity.' }),
  materialWage: symbol({ id: 'material-wage', latex: '\\psi_m', name: 'Material wage', plainPhrase: 'material concessions', meaning: 'Real economic concessions that perform material work.' }),
} as const;

export type EquationSymbolKey = keyof typeof equationSymbols;
